### ISSUE TITLE
Format error with IRAFs CITATION.cff

### ISSUE THREAD

**Issue by olebole** [citation-file-format/ruby-cff#122]
Hi,

not sure whether it belongs here or to a Github implementation issue (please redirect me if needed): I created a [`CITATION.cff`](https://github.com/iraf-community/iraf/blob/fc02bd84c104670616953ea7b66668181b1e0c76/CITATION.cff) for the [iraf repository](https://github.com/iraf-community/iraf). This file [passes the verification with **cffconvert**](https://github.com/iraf-community/iraf/actions/runs/5305335582/jobs/9602230943), but Github seems not be able to parse it:

> Your CITATION.cff file cannot be parsed. Make sure the formatting is correct. [Learn more about CITATION files.](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files)

Unfortunately, there is no more information from Github here, but since Github uses **ruby-cff**, I guess that the error comes from there.
May someone have a look why the parsing doesn't work despite of **cffconvert** check passed?

**Comment by hainesr** [comment]
Hello,

Thanks for letting me know. I'll check this on the ruby-cff side before escalating to GitHub. I'll get back to you ASAP.

Rob

**Comment by hainesr** [comment]
Hello,

Your CITATION.cff file is fine, and is valid. Ruby-cff validates it too. I've tracked this issue down to a problem with date parsing in ruby-cff.

The issue is that ruby-cff assumes that the ruby YAML parser parses dates, like `2023-06-24` into ruby `Date` objects, which it does, but not if the date in the YAML is quoted, e.g., `"2023-06-24"`, as in your file.

So I have a bug to fix in ruby-cff to catch this edge-case.

If you want your file to work in GitHub right now I suggest you unquote all your dates (e.g. `"2023-06-24"` -> `2023-06-24`) and I'll fix this as soon as I can.

I'll leave this issue open to track progress.
