### ISSUE TITLE
Is this "citation" indexed by anyone?

### ISSUE THREAD

**Issue by StellaAthena** [citation-file-format/ruby-cff#80]
For better or for worse, academic search engines are the _de facto_ determiner of value in the academic world. Will Google Scholar, Semantic Scholar, etc. consider GitHub repos with a `CITATION.cff` file an academic object? And will it track citations in academic papers using that identifier?

**Comment by arfon** [comment]
I think this is a question for these platforms (Google Scholar, Semantic Scholar) rather than this project but it's an excellent question. A couple of thoughts:

- In many cases the `CITATION.cff` file is pointing to another record (e.g., a Zenodo DOI, or a paper in a journal). In those cases I would expect these search engines to be indexing those platforms.
- In the case when the `CITATION.cff` file only includes descriptive information about the GitHub repository (i.e., no link to Zenodo, figshare...) then I agree that a `CITATION.cff` file would be a good signal to these platforms that this work is _scholarly_ and perhaps should be indexed. Again though, this seems something mostly in their hands but perhaps something that could be advocated for within our respective communities.

**Comment by StellaAthena** [comment]
> I think this is a question for these platforms (Google Scholar, Semantic Scholar) rather than this project but it's an excellent question. A couple of thoughts:
> 
>     * In many cases the `CITATION.cff` file is pointing to another record (e.g., a Zenodo DOI, or a paper in a journal). In those cases I would expect these search engines to be indexing those platforms.
> 
>     * In the case when the `CITATION.cff` file only includes descriptive information about the GitHub repository (i.e., no link to Zenodo, figshare...) then I agree that a `CITATION.cff` file would be a good signal to these platforms that this work is _scholarly_ and perhaps should be indexed. Again though, this seems something mostly in their hands but perhaps something that could be advocated for within our respective communities.

Yeah, my understanding is that GS ignores you if you don't have enough institutional support behind you unfortunately. This is a big problem for smaller researchers, for example despite being registered on Zenodo [my GPT-Neo codebase](https://scholar.google.com/scholar?start=0&q=%22GPT-Neo%22+%22language%22&hl=en&as_sdt=0,9) has 3 citations according to Google Scholar despite the fact that it clearly identifies 17 citing papers.
